### ISSUE TITLE
Arbitrum RPC node on Akash Network

### ISSUE THREAD

**Issue by Dimokus88** [Dimokus88/Tasks#3]
The scan is successful with the standard image. 
However, synchronization takes a long time. It is recommended to use `persistens storage`.
Last step - create guide.

```
---
version: "2.0"

services:
  app:
    image: offchainlabs/arb-node:v1.4.5-e97c1a4
    args:
      - '--l1.url=' #Ethereum node RPC address

    expose:
      - port: 8545
        to:
          - global: true
      - port: 8546
        to:
          - global: true
      - port: 8547
        to:
          - global: true
    params:
      storage:
        data:
          mount: /root/.arbitrum/
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 3
        memory:
          size: 5Gi
        storage:
        - size: 1Gi
        - name: data
          size: 300Gi
          attributes:
              persistent: true
              class: beta3          
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
```
